version: '3.8'

services:

  # ---------------- MySQL Databases (with volume & healthcheck) ----------------
  mysql-order:
    image: mysql:8
    container_name: mysql-order
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-order-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-net

  mysql-payment:
    image: mysql:8
    container_name: mysql-payment
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: paydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-payment-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-net

  mysql-product:
    image: mysql:8
    container_name: mysql-product
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-product-data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-net

  mysql-user:
    image: mysql:8
    container_name: mysql-user
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-user-data:/var/lib/mysql
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ms-net

  # ---------------- Eureka Server ----------------
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      - mysql-order
      - mysql-payment
      - mysql-product
      - mysql-user
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

  # ---------------- Microservices ----------------
  order-service:
    build: ./order-service
    container_name: order-service
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
      - mysql-order
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
      - mysql-payment
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-payment:3306/paydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

  product-service:
    build: ./product-service
    container_name: product-service
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      - eureka-server
      - mysql-product
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8084:8080"
    depends_on:
      - eureka-server
      - mysql-user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

  # ---------------- API Gateway ----------------
  rapi-gateway:
    build: ./rapi-gateway
    container_name: rapi-gateway
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      - eureka-server
      - user-service
      - order-service
      - payment-service
      - product-service
    environment:
      - SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - ms-net

# ---------------- Volumes ----------------
volumes:
  mysql-order-data:
  mysql-payment-data:
  mysql-product-data:
  mysql-user-data:

# ---------------- Network ----------------
networks:
  ms-net:
    driver: bridge
