version: '3.8'
services:

  # ---------------- MySQL Databases ----------------
  mysql-order:
    image: mysql:8
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mysql-payment:
    image: mysql:8
    environment:
      MYSQL_DATABASE: paydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  mysql-product:
    image: mysql:8
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  mysql-user:
    image: mysql:8
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"

  # ---------------- Eureka Server ----------------
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # ---------------- Microservices ----------------
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mysql-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/orderdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mysql-payment
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-payment:3306/paydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mysql-product
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-product:3306/productdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mysql-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/userdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # ---------------- API Gateway ----------------
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - user-service
      - order-service
      - payment-service
      - product-service
