server:
  port: 8089

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/paydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus  # or use "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: user-service
    description: This is the User Service
    version: 1.0.0